# Generated by Django 6.0.5 on 2026-05-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_camisola', models.PositiveIntegerField(unique=True)),
                ('posicao', models.CharField(choices=[('GR', 'Guarda Redes'), ('FX', 'Fixo'), ('AL', 'Ala'), ('PI', 'Pivot')], max_length=2)),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
