# Generated by Django 6.0.5 on 2026-05-06 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_camisola', models.PositiveIntegerField(unique=True)),
                ('posicao', models.CharField(choices=[('GR', 'Guarda Redes'), ('FX', 'Fixo'), ('AL', 'Ala'), ('PI', 'Pivot')], max_length=2)),
                ('data_nascimento', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adversario', models.CharField(max_length=100)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('is_casa', models.BooleanField(default=True)),
                ('golos_nos', models.IntegerField(blank=True, null=True)),
                ('golos_adv', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('golos', models.IntegerField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='clube.jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas', to='clube.jogo')),
            ],
            options={
                'unique_together': {('jogo', 'jogador')},
            },
        ),
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias', to='clube.jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convocatorias', to='clube.jogo')),
            ],
            options={
                'unique_together': {('jogo', 'jogador')},
            },
        ),
    ]
