# Generated by Django 6.0.5 on 2026-05-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificacaoEquipa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('jogos', models.IntegerField(default=0)),
                ('vitorias', models.IntegerField(default=0)),
                ('empates', models.IntegerField(default=0)),
                ('derrotas', models.IntegerField(default=0)),
                ('golos_marcados', models.IntegerField(default=0)),
                ('golos_sofridos', models.IntegerField(default=0)),
                ('pontos', models.IntegerField(default=0)),
                ('is_nos', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-pontos', '-golos_marcados'],
            },
        ),
    ]
