# Generated by Django 6.0.5 on 2026-05-14 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_classificacaoequipa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('local', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmacao', models.BooleanField(blank=True, default=False, null=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_treino', to='clube.jogador')),
                ('treino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='clube.treino')),
            ],
        ),
    ]
