# Generated by Django 6.0.5 on 2026-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0002_classificacaoequipa'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_jogadores/'),
        ),
    ]
