# Generated by Django 6.0.5 on 2026-05-18 18:22
# Generated by Django 6.0.5 on 2026-05-15 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0003_jogador_foto'),
        ('clube', '0003_treino_presenca'),
    ]

    operations = [
    ]
