# Generated by Django 6.0.5 on 2026-05-19 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0003_jogador_foto'),
        ('clube', '0003_treino_presenca'),
    ]

    operations = [
    ]
