# Generated by Django 6.0.5 on 2026-05-19 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clube', '0004_merge_0003_jogador_foto_0003_treino_presenca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='jogador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_treino', to=settings.AUTH_USER_MODEL),
        ),
    ]
